steps:
# Pull the latest gcloud image.
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['pull', 'gcr.io/cloud-builders/gcloud']
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '--tag=gcr.io/$PROJECT_ID/git', '.']

# Clone the funretro repo
- name: 'gcr.io/cloud-builders/git'
  args: [ 'clone', 'https://github.com/funretro/distributed.git']

# Build the docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/funretro-docker', '.']
  timeout: 500s

images:
- 'gcr.io/$PROJECT_ID/funretro-docker'

