steps:
# Clone the funretro repo
- name: 'gcr.io/cloud-builders/git'
  args: [ 'clone', 'https://github.com/funretro/distributed.git']

# Build the firebase-tools
 name: 'gcr.io/cloud-builders/docker'
 args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/firebase', './firebase']

# Build the docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/funretro-docker', '.']
  timeout: 500s

images:
- 'gcr.io/$PROJECT_ID/funretro-docker'
  'gcr.io/$PROJECT_ID/firebase'

